from D2Shared.shared.enums import AreaEnum

UNSUB_AREAS: list[str] = [AreaEnum.INCARNAM, AreaEnum.ASTRUB]
FARMABLE_SUB_AREAS_BY_AREA: dict[str, list[str]] = {
    AreaEnum.INCARNAM: [
        "Lac",
        "Forêt",
        "Champs",
        "Pâturages",
        "Cimetière",
        "Route des âmes",
    ],
    AreaEnum.ASTRUB: [
        "Tainéla",
        "Cité d'Astrub",
        "Forêt d'Astrub",
        "Champs d'Astrub",
        "Cimetière d'Astrub",
        "Prairies d'Astrub",
        "Calanques d'Astrub",
    ],
    AreaEnum.AMAKNA: [
        "Port de Madrestam",
        "Montagne des Craqueleurs",
        "Champ des Ingalsse",
        "Forêt d'Amakna",
        "Coin des Bouftous",
        "Cimetière",
        "Village d'Amakna",
        "Territoire des Porcos",
        "Péninsule des gelées",
        "Presqu'île des Dragoeufs",
        "Côte d'Asse",
        "Marécages d'Amakna",
        "Territoire des Bandits",
        "Plaine des Scarafeuilles",
        "Coin des Boos",
        "Château d'Amakna",
        "Clairière de Brouce Boulgoure",
        "Millifutaie",
        "Campagne d'Amakna",
    ],
    AreaEnum.CANIA_PLAIN: [
        "Massif de Cania",
        "Lac de Cania",
        "Champs de Cania",
        "Bois de Litneg",
        "Plaines Rocheuses",
        "Plaine des Porkass",
        "Baie de Cania",
        "Landes de Cania",
        "Dents de Pierre",
        "Pics de Cania",
        "Cirque de Cania",
        "Routes Rocailleuses",
    ],
    AreaEnum.SIDIMOTE_LAND: [
        "Désolation de Sidimote",
        "Gisgoul",
        "Terres Désacrées",
        "Hauts des Hurlements",
        "Route des Roulottes",
        "Marches Magmatiques",
    ],
}
AGRESSIVE_LIMIT = 51
